### ISSUE TITLE
[Bug] Panic when login is unsuccessful.

### ISSUE THREAD

**Issue by jason-riddle** [Netflix-Skunkworks/go-jira#159]
Awesome project! :+1:

Getting the following panic stack trace when attempting to login with basic auth, but the login fails (I believe), so running any other commands fail.

```
[5:56:56] puu562:.jira.d git:(master*) $ jira mine                         [1]
+----------------++--------------+--------------+--------------+------------+--------------+--------------+
| Issue          | Summary                       | Type         | Priority     | Status       | Age        | Reporter     | Assignee     |
+----------------++--------------+--------------+--------------+------------+--------------+--------------+
| PROM-1516      | runtime error: slice bounds out of range
goroutine 1 [running]:
runtime/debug.Stack(0xc42019e990, 0x1431ae0, 0x172a7c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
main.handleExit()
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/cmd/jira/main.go:26 +0x8c
panic(0x1431ae0, 0x172a7c0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
text/template.errRecover(0xc42019f878)
	/usr/local/go/src/text/template/exec.go:137 +0x1d4
panic(0x1431ae0, 0x172a7c0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.TemplateProcessor.func15(0xffffffffffffffe3, 0xc42045bb40, 0x3d, 0x0, 0x0)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli/templates.go:163 +0x141
reflect.Value.call(0x14238e0, 0x14cd820, 0x13, 0x14ae9fa, 0x4, 0xc42027dad0, 0x2, 0x2, 0x14abb40, 0x1, ...)
	/usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x14238e0, 0x14cd820, 0x13, 0xc42027dad0, 0x2, 0x2, 0x140b5e0, 0xc42006e1e0, 0x98)
	/usr/local/go/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc42019f7f8, 0x1425980, 0xc4200c8380, 0x194, 0x14238e0, 0x14cd820, 0x13, 0x150f860, 0xc42027c570, 0x14c7e20, ...)
	/usr/local/go/src/text/template/exec.go:667 +0x4f1
text/template.(*state).evalFunction(0xc42019f7f8, 0x1425980, 0xc4200c8380, 0x194, 0xc42027c5a0, 0x150f860, 0xc42027c570, 0xc4203f8e40, 0x2, 0x2, ...)
	/usr/local/go/src/text/template/exec.go:535 +0x176
text/template.(*state).evalCommand(0xc42019f7f8, 0x1425980, 0xc4200c8380, 0x194, 0xc42027c570, 0x140b5e0, 0xc42006e1e0, 0x98, 0x1425980, 0xc4205f9cc0, ...)
	/usr/local/go/src/text/template/exec.go:432 +0x516
text/template.(*state).evalPipeline(0xc42019f7f8, 0x1425980, 0xc4200c8380, 0x194, 0xc4204c8230, 0x0, 0x0, 0x98)
	/usr/local/go/src/text/template/exec.go:405 +0x10f
text/template.(*state).walk(0xc42019f7f8, 0x1425980, 0xc4200c8380, 0x194, 0x150f7a0, 0xc42027c7b0)
	/usr/local/go/src/text/template/exec.go:231 +0x4a5
text/template.(*state).walk(0xc42019f7f8, 0x1425980, 0xc4200c8380, 0x194, 0x150f9a0, 0xc42027c360)
	/usr/local/go/src/text/template/exec.go:239 +0x11d
text/template.(*state).walkRange.func1(0x140abe0, 0x1754bc0, 0x82, 0x1425980, 0xc4200c8380, 0x194)
	/usr/local/go/src/text/template/exec.go:326 +0x121
text/template.(*state).walkRange(0xc42019f7f8, 0x142fb20, 0xc4205680c0, 0x15, 0xc4203da740)
	/usr/local/go/src/text/template/exec.go:335 +0x2fe
text/template.(*state).walk(0xc42019f7f8, 0x142fb20, 0xc4205680c0, 0x15, 0x150faa0, 0xc4203da740)
	/usr/local/go/src/text/template/exec.go:242 +0x447
text/template.(*state).walk(0xc42019f7f8, 0x142fb20, 0xc4205680c0, 0x15, 0x150f9a0, 0xc4200bd740)
	/usr/local/go/src/text/template/exec.go:239 +0x11d
text/template.(*Template).execute(0xc4200c51c0, 0x150afc0, 0xc4200d0008, 0x142fb20, 0xc4205680c0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:194 +0x1e6
text/template.(*Template).Execute(0xc4200c51c0, 0x150afc0, 0xc4200d0008, 0x142fb20, 0xc4205680c0, 0x0, 0xc42019f908)
	/usr/local/go/src/text/template/exec.go:177 +0x53
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.RunTemplate(0x7ffeefbfec95, 0x5, 0x13f3c60, 0xc420180070, 0x150afc0, 0xc4200d0008, 0x0, 0xc42019f9e8)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli/templates.go:249 +0x14a
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.(*CommonOptions).PrintTemplate(0xc42012cb00, 0x13f3c60, 0xc420180070, 0x1f, 0x150a940)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli/cli.go:225 +0x2e8
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd.CmdList(0xc420196ee0, 0xc42012cc60, 0xc42012cb00, 0x18a54a8, 0x7063)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd/list.go:79 +0xb1
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd.CmdListRegistry.func2(0xc420196ee0, 0xc42012cc60, 0x0, 0x0)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd/list.go:42 +0xc9
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.register.func4(0xc4201c42d0, 0x1010733, 0x143c600)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli/cli.go:182 +0x3e
gopkg.in/Netflix-Skunkworks/go-jira.v1/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc4201b2618, 0xc4201c42d0, 0x0, 0x0)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/vendor/gopkg.in/alecthomas/kingpin.v2/actions.go:28 +0x6d
gopkg.in/Netflix-Skunkworks/go-jira.v1/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc420100b40, 0xc4201c42d0, 0x0, 0x0)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:554 +0xde
gopkg.in/Netflix-Skunkworks/go-jira.v1/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc420100b40, 0xc4201c42d0, 0xc4201fc1a0, 0x1, 0x1, 0x0, 0x0, 0xc420100b40, 0x0)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:390 +0x8f
gopkg.in/Netflix-Skunkworks/go-jira.v1/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc420100b40, 0xc4200d4010, 0x5, 0x5, 0xc4201c4240, 0x0, 0x0, 0x6)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:222 +0x1f2
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.ParseCommandLine(0xc420100b40, 0xc4200d4010, 0x5, 0x5)
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli/usage.go:185 +0xf7
main.main()
	/ext-go/1/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/cmd/jira/main.go:51 +0x466
```

**Comment by coryb** [comment]
Hey, this looks like a bug in our template processing:
https://github.com/Netflix-Skunkworks/go-jira/blob/master/jiracli/templates.go#L163

My hunch is the issue summary for `PROM-1516` is less than 3 bytes long, so the automatic abbreviation code fails, so the short-term hacky fix is to manually update the issue to have a longer summary.  It is just sloppy code we need to fix.

**Comment by coryb** [comment]
Released a fix for this: https://github.com/Netflix-Skunkworks/go-jira/releases/latest
