### ISSUE TITLE
password-source: keyring on FC30 result in "dbus: authentication failed"

### ISSUE THREAD

**Issue by rschmied** [Netflix-Skunkworks/go-jira#250]
similar to the unanswered #216 I've tried to run the tests for github.com/tmc/keyring and they succeed:

```
$ go test -v -tags gnome_keyring github.com/tmc/keyring
=== RUN   TestBasicSetGet
--- PASS: TestBasicSetGet (0.06s)
PASS
ok  	github.com/tmc/keyring	(cached)
$
```
is this a configuration issue on my box or some driver error? Is this combination working for anyone out there (FC30/go-jira/Gnome keyring)?

trace https://pastebin.com/9FvZpaK8

**Comment by deefin** [comment]
Same issue for me

```
$ cat ~/.jira.d/config.yml 
endpoint: https://xxxxxxxxx.atlassian.net
user: xxxxxxxxx
login: xxxxxxxxxxxxxxx
authentication-method: api-token
password-source: keyring
```

cant see the key anywhere in gnome-keyring. 

```
gnome-keyring-3.31.91-1.fc30.x86_64
gnome-keyring-pam-3.31.91-1.fc30.x86_64
```

```
$ jira version
1.0.20
```

**Comment by deefin** [comment]
@rschmied a work around is to remove the `password source` line from your `~/.jira.d/config.yml` and `export JIRA_API_TOKEN=`

**Comment by edubxb** [comment]
After some investigation, I discovered that the build need to use the flag:

`-tags gnome_keyring`

to make it work with GNOME Keyring, as explained in the [tmc/keyring](https://github.com/tmc/keyring) README.

After building it myself, the error changes to:

```
jira login
Gnome-keyring error: <nil>
goroutine 1 [running]:
runtime/debug.Stack(0xc0001a4b68, 0x870380, 0xc000432000)
	/usr/lib/go-1.11/src/runtime/debug/stack.go:24 +0xa7
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.HandleExit()
	/home/edubxb/Area51/floss/go-jira/jiracli/cli.go:45 +0x8c
panic(0x870380, 0xc000432000)
	/usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.(*GlobalOptions).GetPass(0xc0000b7520, 0x0, 0x0)
	/home/edubxb/Area51/floss/go-jira/jiracli/password.go:44 +0xb50
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.(*GlobalOptions).ProvideAuthParams(0xc0000b7520, 0x0)
	/home/edubxb/Area51/floss/go-jira/jiracli/password.go:18 +0x2f
gopkg.in/Netflix-Skunkworks/go-jira%2ev1.NewSession(0x9818c0, 0xc000494000, 0xc0001b57e0, 0x19, 0x97c4a0, 0xc0000b7520, 0x0, 0x0, 0x0)
	/home/edubxb/Area51/floss/go-jira/session.go:32 +0x60
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd.CmdLogin(0xc00016e000, 0xc0000b7520, 0xc0000dc4d0, 0x0, 0x3)
	/home/edubxb/Area51/floss/go-jira/jiracmd/login.go:58 +0x334
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd.CmdLoginRegistry.func2(0xc00016e000, 0xc0000b7520, 0x3, 0xc000010000)
	/home/edubxb/Area51/floss/go-jira/jiracmd/login.go:24 +0x3e
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.register.func4(0xc000524120, 0x40c4a3, 0x883b60)
	/home/edubxb/Area51/floss/go-jira/jiracli/cli.go:241 +0x74
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc00017e6d8, 0xc000524120, 0x0, 0x0)
	/home/edubxb/.local/lib/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc000152b40, 0xc000524120, 0x0, 0x0)
	/home/edubxb/.local/lib/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdf
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc000152b40, 0xc000524120, 0xc00044c090, 0x1, 0x1, 0x0, 0x0, 0xc00044c040, 0x0)
	/home/edubxb/.local/lib/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x8f
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc000152b40, 0xc00044c040, 0x1, 0x1, 0x9, 0xc0001a5470, 0x42bea2, 0x8)
	/home/edubxb/.local/lib/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x1fa
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.register.func2(0xc000156300, 0xc000524000, 0x0, 0x0, 0x0)
	/home/edubxb/Area51/floss/go-jira/jiracli/cli.go:175 +0x241
github.com/coryb/oreo.(*Client).Do(0xc00016e000, 0xc000156300, 0xc000524000, 0x0, 0x0)
	/home/edubxb/.local/lib/go/pkg/mod/github.com/coryb/oreo@v0.0.0-20180804211640-3e1b88fc08f1/oreo.go:417 +0x7ed
github.com/coryb/oreo.(*Client).GetJSON(0xc00016e000, 0xc000145940, 0x2d, 0x1, 0x1, 0xc000145940)
	/home/edubxb/.local/lib/go/pkg/mod/github.com/coryb/oreo@v0.0.0-20180804211640-3e1b88fc08f1/oreo.go:451 +0x1c3
gopkg.in/Netflix-Skunkworks/go-jira%2ev1.GetSession(0x9818c0, 0xc00016e000, 0xc0001b57e0, 0x19, 0x0, 0x0, 0x0)
	/home/edubxb/Area51/floss/go-jira/session.go:58 +0xb5
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd.CmdLogin(0xc00016e000, 0xc0000b7520, 0xc0000dc4d0, 0x0, 0x3)
	/home/edubxb/Area51/floss/go-jira/jiracmd/login.go:56 +0x2de
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracmd.CmdLoginRegistry.func2(0xc00016e000, 0xc0000b7520, 0x3, 0xc000010000)
	/home/edubxb/Area51/floss/go-jira/jiracmd/login.go:24 +0x3e
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.register.func4(0xc000196480, 0x40c4a3, 0x883b60)
	/home/edubxb/Area51/floss/go-jira/jiracli/cli.go:241 +0x74
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc00017e6d8, 0xc000196480, 0x0, 0x0)
	/home/edubxb/.local/lib/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc000152b40, 0xc000196480, 0x0, 0x0)
	/home/edubxb/.local/lib/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdf
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc000152b40, 0xc000196480, 0xc0001c03f0, 0x1, 0x1, 0x0, 0x0, 0xc000152b40, 0x0)
	/home/edubxb/.local/lib/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x8f
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc000152b40, 0xc0000ac010, 0x1, 0x1, 0xc0001963f0, 0x0, 0x0, 0xc00013e600)
	/home/edubxb/.local/lib/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x1fa
gopkg.in/Netflix-Skunkworks/go-jira.v1/jiracli.ParseCommandLine(0xc000152b40, 0xc0000ac010, 0x1, 0x1)
	/home/edubxb/Area51/floss/go-jira/jiracli/usage.go:186 +0xf5
main.main()
	/home/edubxb/Area51/floss/go-jira/cmd/jira/main.go:47 +0x46c
```

so finally, to make it work, I created the password entry in the GNOME Keyring manually by this way:

```
secret-tool store --label='go-jira' username <JIRA_USERNAME> service go-jira xdg:schema org.github.tmc.keyring.Password
```

**Comment by rschmied** [comment]
thanks, need to try this... sounds very promising!

**Comment by edubxb** [comment]
With the latest version the GNOME Keyring support is working again.

**Comment by paoloantinori** [comment]
In case this could be useful to anyone:

if you are using a private Jira server, and you are using a `bearer-token` (so not providing your user's password) you need to use this key to store your user: `'api-token:YOUR_EMAIL_HERE'` .

```
secret-tool store --label='go-jira' username 'api-token:YOUR_EMAIL_HERE' service go-jira xdg:schema org.github.tmc.keyring.Password
```

You can verify what is going to be the correctly lookup expanding this logging line: 
https://github.com/go-jira/jira/blob/master/jiracli/password.go#L61

Worked for me on issues.rehdat.com

**Comment by thearifismail** [comment]
> @rschmied a work around is to remove the `password source` line from your `~/.jira.d/config.yml` and `export JIRA_API_TOKEN=`

This does not work for me.  That's why I submitted the issue #477 in this repo.
