### ISSUE TITLE
panic creating issue when createmeta returns empty issuetypes

### ISSUE THREAD

**Issue by blalor** [Netflix-Skunkworks/go-jira#28]
```
> jira create 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Netflix-Skunkworks/go-jira.(*Cli).CmdCreate(0xc820017e00, 0x0, 0x0)
	…/go-jira/src/github.com/Netflix-Skunkworks/go-jira/commands.go:236 +0xfc1
main.main()
	…/go-jira/main/main.go:338 +0x3be5
```

That corresponds to [this line](https://github.com/Netflix-Skunkworks/go-jira/blob/6a88bb9c008fda37f8a986af6da0af35a89c60ea/commands.go#L236)

Running that with a few `-v`s, I ended up with this:

```
>jira request '/rest/api/2/issue/createmeta?projectKeys=SYS&issuetypeNames=Bug&expand=projects.issuetypes.fields'
{
    "expand": "projects",
    "projects": [
        {
            "avatarUrls": {
                "16x16": "https://jira.example.com/secure/projectavatar?size=xsmall\u0026avatarId=10011",
                "24x24": "https://jira.example.com/secure/projectavatar?size=small\u0026avatarId=10011",
                "32x32": "https://jira.example.com/secure/projectavatar?size=medium\u0026avatarId=10011",
                "48x48": "https://jira.example.com/secure/projectavatar?avatarId=10011"
            },
            "expand": "issuetypes",
            "id": "10070",
            "issuetypes": [],
            "key": "SYS",
            "name": "Sysadmin",
            "self": "https://jira.example.com/rest/api/2/project/10070"
        }
    ]
}
```

**Comment by blalor** [comment]
I also get a panic on `jira createmeta`.

**Comment by blalor** [comment]
Ah, I think this is because "Bug" isn't a valid issuetype for this project.

**Comment by coryb** [comment]
Interesting, let me get a check for that added.

**Comment by coryb** [comment]
I pushed out a change for this and published a new release.  Hopefully it will at least produce an error message now rather than a panic.  Thanks
-Cory
